### PR TITLE
Extend events system, make mouse handling consistent

### LINKED ISSUE #1760: Multiple Screens not working
** Updated with requested info. 
Macos htop v 3.4.1 (installed via HomeBrew)
Ubuntu v 3.4.0 (lastest available using apt)

Tried on macOS (direct) and Ubuntu (VMware running on macOS) with same results
1. When adding a new screen, you can add new columns immediately, but if you try to go back and edit that screen definition, only the columns for the main screen show. 
**Added: When you go back to the screen definition in setup and select the new screen, the list of active columns doesn't change. If you add or remove a column, it modifies the main screen rather than the new screen. this happens even if you have 3 screens defined; regardless of which screen is selected, the list of active columns doesn't change and only the main screen gets modified

2. If you try to add EXE as a column it crashes on save   Error information:
------------------
A signal 6 (Aborted) was received
3966 abort (core dumped)  htop

Backtrace from macOS 
Backtrace information:
----------------------
0   htop                                0x0000000102af3b2c CRT_handleSIGSEGV + 288
1   libsystem_platform.dylib            0x000000018bf396a4 _sigtramp + 56
2   libsystem_pthread.dylib             0x000000018beff88c pthread_kill + 296
3   libsystem_c.dylib                   0x000000018be08a3c abort + 124
4   libsystem_malloc.dylib              0x000000018bd0c174 malloc_vreport + 892
5   libsystem_malloc.dylib              0x000000018bd0fc90 malloc_report + 64
6   libsystem_malloc.dylib              0x000000018bd1421c ___BUG_IN_CLIENT_OF_LIBMALLOC_POINTER_BEING_FREED_WAS_NOT_ALLOCATED + 32
7   htop                                0x0000000102af76e0 ListItem_delete + 24
8   htop                                0x0000000102b069d8 Vector_delete + 64
9   htop                                0x0000000102afb464 Panel_done + 32
10  htop                                0x0000000102afb144 Panel_delete + 20
11  htop                                0x0000000102b069d8 Vector_delete + 64
12  htop                                0x0000000102b00b98 ScreenManager_delete + 24
13  htop                                0x0000000102aef270 actionSetup + 92
14  htop                                0x0000000102af80b8 MainPanel_eventHandler + 276
15  htop                                0x0000000102b0138c ScreenManager_run + 1204
16  htop                                0x0000000102af1f0c CommandLine_run + 1872
17  dyld                                0x000000018bb5eb98 start + 6076

Backtrace from Ubuntu
Backtrace information:
----------------------
htop(CRT_handleSIGSEGV+0x124) [0xc7984c26e884]
linux-vdso.so.1(__kernel_rt_sigreturn+0x0) [0xf129db3609a0]
/lib/aarch64-linux-gnu/libc.so.6(+0x8a460) [0xf129db05a460]
/lib/aarch64-linux-gnu/libc.so.6(gsignal+0x20) [0xf129db0076c0]
/lib/aarch64-linux-gnu/libc.so.6(abort+0x2c) [0xf129daff1ac8]
/lib/aarch64-linux-gnu/libc.so.6(+0x7d2c8) [0xf129db04d2c8]
/lib/aarch64-linux-gnu/libc.so.6(+0x959fc) [0xf129db0659fc]
/lib/aarch64-linux-gnu/libc.so.6(+0x97de4) [0xf129db067de4]
/lib/aarch64-linux-gnu/libc.so.6(__libc_free+0x198) [0xf129db06ae20]
htop(+0x2c60c) [0xc7984c27c60c]
htop(Vector_delete+0x70) [0xc7984c27d598]
htop(+0x2de4c) [0xc7984c27de4c]
htop(Vector_delete+0x70) [0xc7984c27d598]
htop(+0x1a510) [0xc7984c26a510]
htop(+0x2af34) [0xc7984c27af34]
htop(ScreenManager_run+0x2b0) [0xc7984c2840c0]
htop(CommandLine_run+0x91c) [0xc7984c26d5fc]
/lib/aarch64-linux-gnu/libc.so.6(+0x222dc) [0xf129daff22dc]
/lib/aarch64-linux-gnu/libc.so.6(__libc_start_main+0x9c) [0xf129daff23bc]
htop(_start+0x30) [0xc7984c262d30]

### PR DESCRIPTION
**Pull request by fasterit**
Fixes: #1760
Improves over: #1783

Extends the events with a lost focus one and makes the screens, meters and columns editing handle that properly.
Since we have that consistent then, I spliced out the second commit to also make the function bar consistent between the meters and the screens setup. The meters one was a bit out-of-the-usual. The shortcuts (space to change meter mode ("style"), enter to accept, cursor keys to move) all still work.

When playing around in Setup for hours the UI inconsistency ... hurts ... so I fixed that quite early but I want to give you all the bikeshedding options :smile:. Commit #1 builds fine separately.

Assisted-by: Microsoft Copilot/Claude Sonnet 4.6

### CODE REVIEW

**Review by BenBE — APPROVED** [review]
LGTM.

File: ColumnsPanel.c [hunk 1]
```diff
@@ -33,6 +34,17 @@ static void ColumnsPanel_delete(Object* object) {
    free(this);
 }
 
+static void ColumnsPanel_cancelMoving(ColumnsPanel* this) {
```
Comment (Explorer09) [inline ColumnsPanel.c:37]: Does this function work only if `this->moving` is true?

I see a room to improve the quality of this code. Maybe I should file a PR for it. For example, moving the `this->moving` conditionals from the callers to here.

Comment (fasterit) [reply ColumnsPanel.c:37]: not worth it imo. The "local" checks are unlikely to succeed and faster than unconditional function calls with all the stack magic and `call`/`ret`.

Comment (Explorer09) [reply ColumnsPanel.c:37]: > not worth it imo. The "local" checks are unlikely to succeed and faster than unconditional function calls with all the stack magic and `call`/`ret`.

I consider it's the compiler's job to move the `this->moving` flag check to outside the function for performance. My reason for putting it in the function is to make it safer (think of when a future developer calls the function without checking the state first). Also it's less redundancy in the source code level.

Comment (fasterit) [reply ColumnsPanel.c:37]: ... on the price of reduced readability. We both have good arguments but this is a matter of taste in the end.
