### PR TITLE
Fix all_branches_collapsed setting

### LINKED ISSUE #1019: always expanded in tree view
hi!
i like using htop, but ive had an issue thats really annoying.
i like to use the tree view in htop, as you can collapse all the programs to make it look very clean and i do have it set to always collapse.
however, when i open htop, everything is expanded again and i dont know why. any help on this is appreciated, i will also include my htoprc.

```
htop_version=3.2.0
config_reader_min_version=3
fields=0 39 46 48 1
hide_kernel_threads=1
hide_userland_threads=1
shadow_other_users=1
show_thread_names=0
show_program_path=0
highlight_base_name=0
highlight_deleted_exe=1
highlight_megabytes=1
highlight_threads=1
highlight_changes=1
highlight_changes_delay_secs=3
find_comm_in_cmdline=1
strip_exe_from_cmdline=1
show_merged_command=1
header_margin=1
screen_tabs=0
detailed_cpu_time=0
cpu_count_from_one=1
show_cpu_usage=1
show_cpu_frequency=0
show_cpu_temperature=0
degree_fahrenheit=0
update_process_names=0
account_guest_in_cpu_meter=0
color_scheme=5
enable_mouse=1
delay=15
hide_function_bar=0
header_layout=two_50_50
column_meters_0=Date AllCPUs4
column_meter_modes_0=2 1
column_meters_1=Clock CPU Memory Tasks
column_meter_modes_1=2 1 1 2
tree_view=1
sort_key=39
tree_sort_key=39
sort_direction=-1
tree_sort_direction=-1
tree_view_always_by_pid=0
all_branches_collapsed=1
screen:Main=PID M_RESIDENT PERCENT_CPU USER Command
.sort_key=M_RESIDENT
.tree_sort_key=M_RESIDENT
.tree_view=1
.tree_view_always_by_pid=0
.sort_direction=-1
.tree_sort_direction=-1
.all_branches_collapsed=1
screen:I/O=PID USER IO_PRIORITY IO_RATE IO_READ_RATE IO_WRITE_RATE PERCENT_SWAP_DELAY PERCENT_IO_DELAY Command
.sort_key=IO_RATE
.tree_sort_key=PID
.tree_view=0
.tree_view_always_by_pid=0
.sort_direction=-1
.tree_sort_direction=1
.all_branches_collapsed=1
```

### PR DESCRIPTION
**Pull request by tanriol**
Should fix #1019.

### CODE REVIEW

File: ProcessList.c [hunk 1]
```diff
@@ -354,6 +354,8 @@ void ProcessList_expandTree(ProcessList* this) {
 }
 
 void ProcessList_collapseAllBranches(ProcessList* this) {
+   ProcessList_buildTree(this); // Update `tree_depth` fields of the processes
+   this->needsSort = true; // Avoid toposort on startup with collapseAllBranches + !treeView
```
Comment (fasterit) [inline ProcessList.c:358]: What is "toposort"? Can you clarify the comment / the rationale?

Comment (tanriol) [reply ProcessList.c]: Elaborated the comment a bit. This is a failsafe for the case if, after some changes, `ProcessList_collapseAllBranches` starts being called in non-tree mode while the process list is already sorted. In that case `ProcessList_buildTree` would change sort order to "by effective parent PID", and the code that preserves the sort order to avoid processes jumping around would preserve this incorrect sort order. Right now this does not happen anyway because the shortcut is inactive in flat mode (2nd patch) and the initial call on startup happens before the list is sorted for the first time.
